/**
 * Public legal documents (Privacy Policy, Terms of Service, Referral Programme
 * Terms). DRAFT — to be reviewed and amended by a qualified solicitor before
 * production reliance. Company-specific placeholders are marked in [SQUARE
 * BRACKETS] for completion.
 *
 * Terms of Service reuses the signed Community Agreement content so the public
 * page and the in-app agreement never drift.
 */
import { AGREEMENT_SECTIONS, AGREEMENT_EFFECTIVE, type AgreementSection } from './agreementContent';

export interface LegalDoc {
  key: string;
  title: string;
  effective: string;
  sections: AgreementSection[];
}

const COMPANY = 'Apricoti Ltd';
const OFFICE = '[Registered office address]';
const COMPANY_NO = '[Company number]';
const ICO_NO = '[ICO registration number]';
const SUPPORT = 'info@apricoti.co.uk';

// ---------------------------------------------------------------------------
// Privacy Policy
// ---------------------------------------------------------------------------
export const PRIVACY_POLICY: LegalDoc = {
  key: 'privacy',
  title: 'Privacy Policy',
  effective: AGREEMENT_EFFECTIVE,
  sections: [
    {
      id: 'who-we-are',
      title: '1. Who we are',
      body: [
        `${COMPANY} ("Apricoti", "we", "us") provides a social-companionship video-call service. We are the data controller for the personal data processed through the service.`,
        `Registered office: ${OFFICE}. Company number: ${COMPANY_NO}. ICO registration: ${ICO_NO}.`,
        `Questions about this policy or your data can be sent to ${SUPPORT}.`,
      ],
    },
    {
      id: 'what-we-collect',
      title: '2. The personal data we collect',
      body: [
        '• Account & profile data: name, preferred name, email, role (member, coordinator or companion), country of residence, languages, interests, and — for companions — profile, headline, bio, pricing and availability.',
        '• Booking & activity data: bookings, conversations, attendance, reviews, and the messages and notifications generated by using the service.',
        '• Payment data: records of payments, payouts, refunds and account credit. Card and bank details are collected and held by our payment processor (Stripe), not by us.',
        '• Verification data: for companions, a short identity video recorded during verification (see retention below).',
        '• Support & safety data: reports, concerns, and information needed to keep people safe.',
        '• Technical data: information needed to operate the app and video calls (e.g. session and device information).',
      ],
    },
    {
      id: 'why-lawful-basis',
      title: '3. Why we use it, and our lawful bases',
      body: [
        'We use personal data to provide and operate the service, arrange and run conversations, take payments and make payouts, keep people safe, provide support, and improve the service.',
        'Our lawful bases under UK GDPR are: performance of our contract with you; our legitimate interests (running, securing and improving the service, preventing fraud and abuse, and safeguarding); compliance with legal obligations (for example financial, tax and safeguarding duties); and consent where required (for example non-essential community and programme emails).',
        'We do not sell your personal data, and we do not use it for third-party advertising.',
      ],
    },
    {
      id: 'verification-videos',
      title: '4. Companion verification videos',
      body: [
        'Companion identity videos are stored in a private, access-controlled location and are visible only to the companion who recorded the video and our support team, solely to verify identity.',
        'Verification videos are permanently deleted once verification is complete (whether approved or rejected). They are not shared with members or coordinators and are not used to train any automated system.',
      ],
    },
    {
      id: 'sharing',
      title: '5. Who we share data with',
      body: [
        'We use trusted providers who process data on our behalf under contract: Stripe (payments and payouts), LiveKit (video calls), Supabase (secure database and file storage), Vercel (application hosting) and Resend (email delivery). Some may process data outside the UK; where they do, appropriate safeguards (such as UK/EU-approved transfer mechanisms) are in place.',
        'We may share information with the police, a local authority or other authorities where necessary to protect a person at risk, to comply with the law, or to prevent or detect crime.',
        'Between users, we share only the minimum necessary for a conversation to take place; members’ private details are not disclosed to companions beyond what is required.',
      ],
    },
    {
      id: 'retention',
      title: '6. How long we keep data',
      body: [
        '• Verification videos: deleted on completion of verification.',
        '• Account and profile data: kept while your account is active, then deleted or anonymised after closure, subject to the records below.',
        '• Financial records (payments, payouts, refunds, tax): kept for at least six years as required by law.',
        '• Safeguarding and trust-and-safety records: kept as long as necessary to protect people and meet our legal duties.',
        '• Messages and conversation metadata: kept for a limited period to support safety and dispute resolution, then deleted or anonymised.',
      ],
    },
    {
      id: 'your-rights',
      title: '7. Your rights',
      body: [
        'You have the right to access your data, to have inaccurate data corrected, to have data deleted in certain circumstances, to restrict or object to certain processing, and to data portability. Where we rely on consent, you can withdraw it at any time.',
        `To exercise any right, contact ${SUPPORT}. We will respond within the time limits set by law.`,
        'If you are unhappy with how we handle your data, you can complain to the Information Commissioner’s Office (ICO) at ico.org.uk — though we ask that you contact us first so we can try to put things right.',
      ],
    },
    {
      id: 'security-children-changes',
      title: '8. Security, children, and changes',
      body: [
        'Security: we protect data with access controls, encryption in transit, row-level database security and least-privilege access. No system is perfectly secure, but we take reasonable steps to protect your information and will notify you and the ICO of a personal data breach where the law requires.',
        'Children: the service is for adults (18+) and is not directed at children.',
        'Changes: we may update this policy; the version and date are shown at the top. Material changes will be brought to your attention.',
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Referral Programme Terms
// ---------------------------------------------------------------------------
export const REFERRAL_TERMS: LegalDoc = {
  key: 'referral-terms',
  title: 'Referral Programme Terms',
  effective: AGREEMENT_EFFECTIVE,
  sections: [
    {
      id: 'overview',
      title: '1. Overview',
      body: [
        'Apricoti’s introduction (referral) programme rewards existing members of the Apricoti community for introducing a genuinely new person or household to the service. These terms govern participation and sit alongside our Terms of Service and Privacy Policy.',
        'This is a limited pilot. Apricoti may review, pause, change or end the programme at any time, while honouring rewards already validly earned.',
      ],
    },
    {
      id: 'how-it-works',
      title: '2. How it works',
      body: [
        '• Share your personal Apricoti invite link or code. Please do not send us anyone’s personal details — the person must choose to register themselves, or give appropriate consent.',
        '• The person you introduce creates their own account and can book a free 30-minute trial call.',
        '• If you are a Companion, you then earn in the ordinary way from any paid conversations you go on to have with the people you introduced.',
      ],
    },
    {
      id: 'reward',
      title: '3. The benefit',
      body: [
        'There is no separate cash bounty for making an introduction. For Companions, the benefit is the ongoing paid conversations you have with the members and coordinators you bring to Apricoti — you earn from those calls in the normal way, after Apricoti’s usual processing fee and commission.',
        'Members and coordinators who make introductions are simply helping people they know find companionship; no payment is made for the introduction itself.',
      ],
    },
    {
      id: 'what-counts',
      title: '4. What counts, and what does not',
      body: [
        'A "paid call" is a completed, paid conversation. Trial, cancelled, refunded, disputed, fraudulent or unpaid calls are handled under the normal conversation and payment terms.',
        'The person introduced must be a genuinely new Apricoti user and household. Existing users and self-referrals do not qualify.',
      ],
    },
    {
      id: 'eligibility-limits',
      title: '5. Eligibility and conduct',
      body: [
        'We may review, pause or change how introductions work at any time, and may withhold any benefit where we reasonably believe the programme is being abused or the activity is fraudulent.',
        'If you work professionally as a carer, support worker or in a public-sector role, you may make introductions only where permitted by your employer, contract and professional policies. Apricoti does not offer or pay personal incentives to NHS staff, social prescribers or other public-sector professionals in the course of their duties.',
      ],
    },
    {
      id: 'general',
      title: '6. General',
      body: [
        'The person introduced must consent to participating. Earnings from conversations are paid under the normal Apricoti payment terms and may be treated as taxable income in your own circumstances — you are responsible for any tax due.',
        `Questions about introductions can be sent to ${SUPPORT}.`,
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Terms of Service — the signed Community Agreement, shown publicly.
// ---------------------------------------------------------------------------
export const TERMS_OF_SERVICE: LegalDoc = {
  key: 'terms',
  title: 'Terms of Service',
  effective: AGREEMENT_EFFECTIVE,
  sections: AGREEMENT_SECTIONS,
};

export const LEGAL_DOCS: Record<string, LegalDoc> = {
  privacy: PRIVACY_POLICY,
  'referral-terms': REFERRAL_TERMS,
  terms: TERMS_OF_SERVICE,
};
